add

diff --git a/0x00-python-hello_world/101-compile b/0x00-python-hello_world/101-compile
--- a/0x00-python-hello_world/101-compile
+++ b/0x00-python-hello_world/101-compile
@@ -1,8 +1,20 @@
 #!/bin/bash
-python3 -m compileall -b $PYFILE
 
+if [ -z "$PYFILE" ]; then
+    echo "Error: Environment variable PYFILE not set."
+    exit 1
+fi
+
+# Compile the Python script
+python3 -m compileall -b "$PYFILE"
+
+# Check if compilation was successful
 if [ $? -eq 0 ]; then
-    echo "1"
+    echo "Compiling $PYFILE ..."
+    compiled_filename="${PYFILE}c"
+    mv "__pycache__/$compiled_filename" .
+    rm -rf "__pycache__"
+    ls -l "$compiled_filename"
 else
-    echo "0"
+    echo "Compilation failed."
 fi
